// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered resume demo flow.
 *
 * - generateAiResumeDemo - A function that generates a sample resume based on a job title.
 * - AiResumeDemoInput - The input type for the generateAiResumeDemo function.
 * - AiResumeDemoOutput - The return type for the generateAiResumeDemo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiResumeDemoInputSchema = z.object({
  jobTitle: z.string().describe('The job title to generate a sample resume for.'),
});
export type AiResumeDemoInput = z.infer<typeof AiResumeDemoInputSchema>;

const AiResumeDemoOutputSchema = z.object({
  resume: z.string().describe('The generated sample resume.'),
});
export type AiResumeDemoOutput = z.infer<typeof AiResumeDemoOutputSchema>;

export async function generateAiResumeDemo(input: AiResumeDemoInput): Promise<AiResumeDemoOutput> {
  return aiResumeDemoFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiResumeDemoPrompt',
  input: {schema: AiResumeDemoInputSchema},
  output: {schema: AiResumeDemoOutputSchema},
  prompt: `You are an expert resume writer. Generate a sample resume with a basic summary, skills, and experience sections based on the following job title: {{{jobTitle}}}.`,
});

const aiResumeDemoFlow = ai.defineFlow(
  {
    name: 'aiResumeDemoFlow',
    inputSchema: AiResumeDemoInputSchema,
    outputSchema: AiResumeDemoOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
