// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview An AI-powered resume text rewriter.
 *
 * - rewriteResumeText - A function that rewrites a given piece of resume text.
 * - RewriteResumeTextInput - The input type for the rewriteResumeText function.
 * - RewriteResumeTextOutput - The return type for the rewriteResumeText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RewriteResumeTextInputSchema = z.object({
  textToRewrite: z.string().describe('The resume text to be rewritten and improved.'),
  jobTitle: z.string().optional().describe('The user\'s job title for additional context.'),
});
export type RewriteResumeTextInput = z.infer<typeof RewriteResumeTextInputSchema>;

const RewriteResumeTextOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of 3-5 rewritten suggestions for the provided text.'),
});
export type RewriteResumeTextOutput = z.infer<typeof RewriteResumeTextOutputSchema>;

export async function rewriteResumeText(input: RewriteResumeTextInput): Promise<RewriteResumeTextOutput> {
  return rewriteResumeTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'rewriteResumeTextPrompt',
  input: {schema: RewriteResumeTextInputSchema},
  output: {schema: RewriteResumeTextOutputSchema},
  prompt: `You are an expert resume editor. Your task is to rewrite and improve the following text from a resume.

DO NOT invent new facts, numbers, or experiences. Focus solely on improving the wording. Use stronger action verbs, enhance clarity, and make the text more impactful and concise.

Provide 3 to 5 alternative versions of the text.

Job Title (for context): {{{jobTitle}}}
Text to rewrite:
"{{{textToRewrite}}}"
`,
});

const rewriteResumeTextFlow = ai.defineFlow(
  {
    name: 'rewriteResumeTextFlow',
    inputSchema: RewriteResumeTextInputSchema,
    outputSchema: RewriteResumeTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
